//! Cross-implementation test vectors (`testdata/vectors.json`), also run by the Android app's port.
//! Regenerate with `WISPRCHEAP_WRITE_VECTORS=1 cargo test -p wisprcheap-sync --test vectors`.

use serde_json::{Value, json};
use wisprcheap_sync::crypto::{self, DataKey, KdfParams, b64, derive_passphrase_key, unb64, unwrap_key};
use wisprcheap_sync::hlc::Hlc;

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/vectors.json");

fn kdf(m: u32, t: u32, p: u32) -> KdfParams {
    KdfParams { alg: "argon2id".into(), m, t, p }
}

fn generate() -> Value {
    let salt: Vec<u8> = (0u8..16).collect();
    let passphrase = "correct horse battery staple \u{2713} caf\u{e9}";
    let fast = kdf(1024, 1, 1);
    let prod = KdfParams::default();
    let key_fast = derive_passphrase_key(passphrase, &salt, &fast).unwrap();
    let key_prod = derive_passphrase_key(passphrase, &salt, &prod).unwrap();
    let dk = DataKey::from_bytes(std::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(3)));
    let user = "usr_test";
    let wrapped = crypto::wrap_key_with_nonce(&key_fast, user, &dk, &[0x22; 12]);
    let records: Vec<Value> = [
        ("setting", "polish.model".to_string(), json!("gpt-6-luna")),
        ("setting", "command.temperature".to_string(), json!({ "inherit": true })),
        ("setting", "polish.reasoningEffort".to_string(), Value::Null),
        ("secret", "openai".to_string(), json!("sk-test-1234567890")),
        ("dict", dk.blind_id("dict", "pnpm"), json!({ "term": "pnpm", "soundsLike": ["p n p m", "pee npm"] })),
        ("pair", dk.blind_id("pair", "auto>en"), json!({ "from": null, "to": "en" })),
        ("history", "0f8fad5b-d9cb-469f-a165-70867728950e".to_string(),
            json!({ "id": "0f8fad5b-d9cb-469f-a165-70867728950e", "ts": "2026-09-29T12:34:56.789Z",
                    "text": "Déjà vu — ✓", "words": 3 })),
    ]
    .into_iter()
    .enumerate()
    .map(|(i, (kind, id, value))| {
        let nonce = [i as u8 + 1; 12];
        json!({
            "userId": user, "kind": kind, "id": id, "value": value, "nonce": b64(&nonce),
            "envelope": dk.encrypt_record_with_nonce(user, kind, &id, &value, &nonce),
        })
    })
    .collect();
    let blind: Vec<Value> = [("dict", "kubernetes"), ("pair", "fr>en"), ("price", "gpt-6-luna")]
        .into_iter()
        .map(|(kind, key)| json!({ "kind": kind, "key": key, "id": dk.blind_id(kind, key) }))
        .collect();
    json!({
        "comment": "Generated by sync/tests/vectors.rs. Every client implementation must reproduce these values.",
        "kdf": [
            { "passphrase": passphrase, "salt": b64(&salt), "params": fast, "key": b64(&key_fast) },
            { "passphrase": passphrase, "salt": b64(&salt), "params": prod, "key": b64(&key_prod) },
            { "passphrase": "correct horse battery staple \u{2713} cafe\u{301}", "salt": b64(&salt), "params": fast,
              "key": b64(&key_fast), "note": "decomposed é: NFC normalisation gives the same key" }
        ],
        "dataKey": { "bytes": b64(dk.as_bytes()), "export": dk.export(), "keyId": dk.key_id() },
        "wrap": { "userId": user, "passphraseKey": b64(&key_fast), "nonce": b64(&[0x22; 12]), "wrappedKey": wrapped },
        "records": records,
        "blindIds": blind,
        "hlc": {
            "sorted": ["1759154400123-0000-dev_b", "1759154400123-0001-dev_a", "1759154400123-0001-dev_b", "1759154400124-0000-dev_a"],
            "invalid": ["1759154400123-0000-", "12-0000-dev_a", "1759154400123-00000-dev_a", "1759154400123-0000-dev a"]
        }
    })
}

#[test]
fn vectors() {
    if std::env::var("WISPRCHEAP_WRITE_VECTORS").is_ok() {
        let text = serde_json::to_string_pretty(&generate()).unwrap() + "\n";
        std::fs::write(PATH, text).unwrap();
    }
    let v: Value = serde_json::from_str(&std::fs::read_to_string(PATH).expect("run with WISPRCHEAP_WRITE_VECTORS=1 once")).unwrap();

    for k in v["kdf"].as_array().unwrap() {
        let params: KdfParams = serde_json::from_value(k["params"].clone()).unwrap();
        let key = derive_passphrase_key(k["passphrase"].as_str().unwrap(), &unb64(k["salt"].as_str().unwrap()).unwrap(), &params).unwrap();
        assert_eq!(b64(&key), k["key"].as_str().unwrap());
    }

    let dk_bytes: [u8; 32] = unb64(v["dataKey"]["bytes"].as_str().unwrap()).unwrap().try_into().unwrap();
    let dk = DataKey::from_bytes(dk_bytes);
    assert_eq!(dk.export(), v["dataKey"]["export"].as_str().unwrap());
    assert_eq!(dk.key_id(), v["dataKey"]["keyId"].as_str().unwrap());

    let w = &v["wrap"];
    let pk: [u8; 32] = unb64(w["passphraseKey"].as_str().unwrap()).unwrap().try_into().unwrap();
    let nonce: [u8; 12] = unb64(w["nonce"].as_str().unwrap()).unwrap().try_into().unwrap();
    let user = w["userId"].as_str().unwrap();
    assert_eq!(crypto::wrap_key_with_nonce(&pk, user, &dk, &nonce), w["wrappedKey"].as_str().unwrap());
    assert_eq!(unwrap_key(&pk, user, w["wrappedKey"].as_str().unwrap()).unwrap().as_bytes(), dk.as_bytes());

    for r in v["records"].as_array().unwrap() {
        let (user, kind, id) = (r["userId"].as_str().unwrap(), r["kind"].as_str().unwrap(), r["id"].as_str().unwrap());
        let nonce: [u8; 12] = unb64(r["nonce"].as_str().unwrap()).unwrap().try_into().unwrap();
        assert_eq!(dk.encrypt_record_with_nonce(user, kind, id, &r["value"], &nonce), r["envelope"].as_str().unwrap());
        assert_eq!(dk.decrypt_record(user, kind, id, r["envelope"].as_str().unwrap()).unwrap(), r["value"]);
    }

    for b in v["blindIds"].as_array().unwrap() {
        assert_eq!(dk.blind_id(b["kind"].as_str().unwrap(), b["key"].as_str().unwrap()), b["id"].as_str().unwrap());
    }

    let sorted: Vec<Hlc> = v["hlc"]["sorted"].as_array().unwrap().iter().map(|s| Hlc::parse(s.as_str().unwrap()).unwrap()).collect();
    assert!(sorted.windows(2).all(|w| w[0] < w[1] && w[0].to_string() < w[1].to_string()));
    for bad in v["hlc"]["invalid"].as_array().unwrap() {
        assert!(Hlc::parse(bad.as_str().unwrap()).is_none(), "{bad}");
    }
}
